version: '3.7'

services:
  app-php:
    build:
      context: ./configs/docker/php/
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: ${WORKDIR}
    volumes:
      - ./app:${WORKDIR}
    networks:
      - app-network

  composer:
    image: composer:2
    working_dir: ${WORKDIR}
    command: [ "composer", "install" ]
    volumes:
      - ./app:${WORKDIR}

networks:
  app-network:
    driver: bridge