#!/usr/bin/env php
<?php declare(strict_types=1);

use Dotenv\Dotenv;
use Symfony\Component\Console\Application;
use App\Command\YandexTaxi;

require __DIR__ . '/vendor/autoload.php';

(Dotenv::createImmutable(__DIR__))->load();

$application = new Application();

$application->add(new YandexTaxi());

$application->run();